# Generated by Django 4.1.3 on 2022-12-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolistitem',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='todolistitem',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
