# Generated by Django 3.1 on 2022-12-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_content_todolistitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
